// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:al_huda/feature/azkar/data/model/zikr.dart';
import 'package:al_huda/feature/doaa/data/model/doaa_model.dart';
import 'package:al_huda/feature/qran/data/model/ayat_model/ayat.dart';
import 'package:al_huda/feature/qran/data/model/ayat_model/edition.dart';
import 'package:al_huda/feature/qran/data/model/ayat_model/surah_model_data.dart';
import 'package:al_huda/feature/qran/data/model/surah_model/surah_data.dart';
import 'package:al_huda/feature/tasbeh/data/model/tasbeh_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AyahAdapter());
    registerAdapter(DoaaModelDataAdapter());
    registerAdapter(EditionAdapter());
    registerAdapter(SurahDataAdapter());
    registerAdapter(SurahModelDataAdapter());
    registerAdapter(TasbehModelAdapter());
    registerAdapter(ZikrAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AyahAdapter());
    registerAdapter(DoaaModelDataAdapter());
    registerAdapter(EditionAdapter());
    registerAdapter(SurahDataAdapter());
    registerAdapter(SurahModelDataAdapter());
    registerAdapter(TasbehModelAdapter());
    registerAdapter(ZikrAdapter());
  }
}
